"""Export Kaptus's Wordbird as SVG and Android vector resources.

This is the editable vector master for the selected paper-bird concept.
Run from any directory with Python 3. No third-party packages are required.
"""

from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1]
BRAND = ROOT / "docs/brand"
RES = ROOT / "app/src/main/res"
TEAL = "#176B70"
ACCENT_YELLOW = "#FFC857"  # Matches ui.theme.SyncAmber.
SCALE = 0.049
# A 3 dp rightward optical correction gives the raised wingtip more space.
TX, TY = 25.15, 23.522

# Keep every point of the bird within Android's central 66 dp safe circle.
# The outer 18 dp of each 108 dp adaptive layer is reserved for launcher effects.
GRADIENTS = {
    "tail": (280, 850, 580, 1010, [(0, "#FFD169"), (1, "#D59A2C")]),
    "body": (810, 420, 540, 1080, [(0, "#FFF9EA"), (1, "#EDE4D0")]),
    "beak": (990, 402, 1090, 470, [(0, "#FFE397"), (1, ACCENT_YELLOW)]),
    "beakFold": (1020, 457, 1035, 526, [(0, "#AF741A"), (1, "#D99C27")]),
    "underwing": (545, 580, 610, 765, [(0, "#9D6819"), (1, "#D9A02B")]),
    "chest": (746, 596, 914, 762, [(0, "#FFE38F"), (1, "#C98D20")]),
    "wing": (241, 199, 698, 641, [(0, "#FFE08A"), (1, ACCENT_YELLOW)]),
}

SLOT_ONE = (
    "M326,298 L540,372 Q560,381 552,402 Q545,420 526,413 "
    "L311,338 Q290,331 299,310 Q307,292 326,298 Z"
)
SLOT_TWO = (
    "M362,419 L561,491 Q584,500 575,520 Q568,537 549,531 "
    "L346,458 Q326,451 334,431 Q342,412 362,419 Z"
)
WING = (
    "M223,140 L593,332 Q618,345 629,371 L773,687 "
    "L352,571 Q315,559 298,509 L197,164 Q188,135 212,137 "
    "Q219,138 223,140 Z"
)

# Paint order follows the paper folds, from the tail to the lifted wing.
PATHS = [
    ("tail", "M555,758 L237,938 Q230,943 241,949 L487,1047 Q591,928 555,758 Z"),
    ("#FFDB79", "M555,758 L237,938 Q230,943 241,949 L331,989 Z"),
    ("body", "M720,570 C796,444 881,340 981,390 L995,512 C1005,789 839,1004 457,1097 Q431,1105 447,1085 C560,1005 602,884 555,758 Z"),
    ("beak", "M981,390 L1094,447 Q1104,452 1094,459 L997,536 L992,464 Z"),
    ("beakFold", "M992,464 L1099,451 L997,536 Z"),
    ("underwing", "M310,541 L773,687 L555,758 Z"),
    ("chest", "M720,570 L936,773 L773,687 Z"),
    ("wing", f"{WING} {SLOT_ONE} {SLOT_TWO}"),
]

SILHOUETTE = (
    "M223,140 L593,332 Q618,345 629,371 L720,570 "
    "C796,444 881,340 981,390 L1094,447 Q1104,452 1094,459 "
    "L997,536 C1005,789 839,1004 457,1097 Q431,1105 447,1085 "
    "Q467,1067 487,1047 L241,949 Q230,943 237,938 L555,758 "
    "L352,571 Q315,559 298,509 L197,164 Q188,135 212,137 "
    f"Q219,138 223,140 Z {SLOT_ONE} {SLOT_TWO}"
)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text + "\n", encoding="utf-8", newline="\n")


def svg(circle: bool) -> str:
    viewport = "18 18 72 72" if circle else "0 0 108 108"
    result = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{viewport}" width="512" height="512" role="img" aria-labelledby="title">',
        "  <title id=\"title\">Kaptus Wordbird</title>",
        "  <!-- Generated by tools/generate_brand_assets.py. -->",
        "  <defs>",
    ]
    for name, (x1, y1, x2, y2, stops) in GRADIENTS.items():
        result.append(f'    <linearGradient id="{name}" gradientUnits="userSpaceOnUse" x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}">')
        result.extend(f'      <stop offset="{offset}" stop-color="{color}"/>' for offset, color in stops)
        result.append("    </linearGradient>")
    result.append("  </defs>")
    if circle:
        result.append(f'  <circle cx="54" cy="54" r="36" fill="{TEAL}"/>')
    result.append(f'  <g transform="translate({TX} {TY}) scale({SCALE})" fill-rule="evenodd">')
    for paint, path in PATHS:
        fill = paint if paint.startswith("#") else f"url(#{paint})"
        result.append(f'    <path fill="{fill}" d="{escape(path)}"/>')
    result.extend(["  </g>", "</svg>"])
    return "\n".join(result)


def vector(monochrome: bool) -> str:
    result = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    xmlns:aapt="http://schemas.android.com/aapt"',
        '    android:width="108dp" android:height="108dp"',
        '    android:viewportWidth="108" android:viewportHeight="108">',
        "    <!-- Generated by tools/generate_brand_assets.py. -->",
        f'    <group android:scaleX="{SCALE}" android:scaleY="{SCALE}" android:translateX="{TX}" android:translateY="{TY}">',
    ]
    paths = [("#FFFFFF", SILHOUETTE)] if monochrome else PATHS
    for paint, path in paths:
        attributes = f'android:fillType="evenOdd" android:pathData="{escape(path)}"'
        if paint.startswith("#"):
            result.append(f'        <path android:fillColor="{paint}" {attributes}/>' )
        else:
            x1, y1, x2, y2, stops = GRADIENTS[paint]
            result.extend([
                f"        <path {attributes}>",
                '            <aapt:attr name="android:fillColor">',
                f'                <gradient android:type="linear" android:startX="{x1}" android:startY="{y1}" android:endX="{x2}" android:endY="{y2}">',
            ])
            result.extend(f'                    <item android:offset="{offset}" android:color="{color}"/>' for offset, color in stops)
            result.extend(["                </gradient>", "            </aapt:attr>", "        </path>"])
    result.extend(["    </group>", "</vector>"])
    return "\n".join(result)


def main() -> None:
    write(BRAND / "kaptus-icon.svg", svg(circle=True))
    write(BRAND / "kaptus-foreground.svg", svg(circle=False))
    write(RES / "drawable/ic_launcher_foreground.xml", vector(monochrome=False))
    write(RES / "drawable/ic_launcher_monochrome.xml", vector(monochrome=True))
    write(RES / "values/brand_colors.xml", f'''<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="kaptus_icon_background">{TEAL}</color>
</resources>''')
    write(RES / "drawable/ic_launcher_background.xml", '''<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <path android:fillColor="@color/kaptus_icon_background" android:pathData="M0,0h108v108h-108z"/>
</vector>''')
    adaptive = '''<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>'''
    for name in ("ic_launcher", "ic_launcher_round"):
        write(RES / f"mipmap-anydpi/{name}.xml", adaptive)
    print("Exported circular SVG badge and adaptive Android vector layers.")


if __name__ == "__main__":
    main()
